#pragma once

/*#include <DOM/Animation/AnimationTimeLine.h>
#include <DOM/Animation/Behavior.h>
#include <DOM/Animation/BehaviorAccumulateType.h>
#include <DOM/Animation/BehaviorAdditiveType.h>*/
#include <DOM/Animation/BehaviorCollection.h>
#include <DOM/Animation/BehaviorFactory.h>/*
#include <DOM/Animation/BehaviorProperty.h>
#include <DOM/Animation/BehaviorPropertyCollection.h>
#include <DOM/Animation/BuildType.h>
#include <DOM/Animation/ColorDirection.h>
#include <DOM/Animation/ColorEffect.h>
#include <DOM/Animation/ColorOffset.h>
#include <DOM/Animation/ColorSpace.h>
#include <DOM/Animation/CommandEffect.h>
#include <DOM/Animation/CommandEffectType.h>*/
#include <DOM/Animation/Effect.h>
#include <DOM/Animation/EffectChartMajorGroupingType.h>
#include <DOM/Animation/EffectChartMinorGroupingType.h>
#include <DOM/Animation/EffectFillType.h>
#include <DOM/Animation/EffectPresetClassType.h>
#include <DOM/Animation/EffectRestartType.h>
#include <DOM/Animation/EffectSubtype.h>
#include <DOM/Animation/EffectTriggerType.h>
#include <DOM/Animation/EffectType.h>
#include <DOM/Animation/FilterEffect.h>
#include <DOM/Animation/FilterEffectRevealType.h>
#include <DOM/Animation/FilterEffectSubtype.h>
#include <DOM/Animation/FilterEffectType.h>
#include <DOM/Animation/MotionCmdPath.h>
#include <DOM/Animation/MotionCommandPathType.h>
#include <DOM/Animation/MotionEffect.h>
#include <DOM/Animation/MotionOriginType.h>
#include <DOM/Animation/MotionPath.h>
#include <DOM/Animation/MotionPathEditMode.h>
#include <DOM/Animation/MotionPathPointsType.h>
#include <DOM/Animation/Point.h>
#include <DOM/Animation/PointCollection.h>
#include <DOM/Animation/PropertyCalcModeType.h>
#include <DOM/Animation/PropertyEffect.h>
#include <DOM/Animation/PropertyValueType.h>
#include <DOM/Animation/RotationEffect.h>
#include <DOM/Animation/ScaleEffect.h>

#include <DOM/Animation/Sequence.h>
#include <DOM/Animation/SequenceCollection.h>
#include <DOM/Animation/SetEffect.h>
#include <DOM/Animation/TextAnimation.h>
#include <DOM/Animation/TextAnimationCollection.h>
#include <DOM/Animation/Timing.h>
