#pragma once

#include <DOM/Chart/AxesManager.h>
#include <DOM/Chart/Axis.h>
#include <DOM/Chart/AxisAggregationType.h>
#include <DOM/Chart/AxisFormat.h>
#include <DOM/Chart/AxisPositionType.h>
#include <DOM/Chart/BubbleSizeRepresentationType.h>
#include <DOM/Chart/CategoryAxisType.h>
#include <DOM/Chart/Chart.h>
#include <DOM/Chart/ChartCategory.h>
#include <DOM/Chart/ChartCategoryCollection.h>
#include <DOM/Chart/ChartCategoryLevelsManager.h>
#include <DOM/Chart/ChartCellCollection.h>
#include <DOM/Chart/ChartData.h>
#include <DOM/Chart/ChartDataPoint.h>
#include <DOM/Chart/ChartDataPointCollection.h>
#include <DOM/Chart/ChartDataPointLevel.h>
#include <DOM/Chart/ChartDataPointLevelsManager.h>
#include <DOM/Chart/ChartDataSourceType.h>
#include <DOM/Chart/ChartLinesFormat.h>
#include <DOM/Chart/ChartPlotArea.h>
#include <DOM/Chart/ChartSeries.h>
#include <DOM/Chart/ChartSeriesCollection.h>
#include <DOM/Chart/ChartSeriesGroup.h>
#include <DOM/Chart/ChartShapeType.h>
#include <DOM/Chart/ChartTitle.h>
#include <DOM/Chart/ChartType.h>
#include <DOM/Chart/ChartWall.h>
#include <DOM/Chart/CombinableSeriesTypesGroup.h>
#include <DOM/Chart/CrossesType.h>
#include <DOM/Chart/DataLabel.h>
#include <DOM/Chart/DataLabelCollection.h>
#include <DOM/Chart/DataLabelFormat.h>
#include <DOM/Chart/DataSourceType.h>
#include <DOM/Chart/DataSourceTypeForErrorBarsCustomValues.h>
#include <DOM/Chart/DataTable.h>
#include <DOM/Chart/DisplayBlanksAsType.h>
#include <DOM/Chart/DisplayUnitType.h>
#include <DOM/Chart/ErrorBarsCustomValues.h>
#include <DOM/Chart/ErrorBarsFormat.h>
#include <DOM/Chart/ErrorBarType.h>
#include <DOM/Chart/ErrorBarValueType.h>
#include <DOM/Chart/Format.h>
#include <DOM/Chart/LayoutTargetType.h>
#include <DOM/Chart/Legend.h>
#include <DOM/Chart/LegendDataLabelPosition.h>
#include <DOM/Chart/LegendEntryCollection.h>
#include <DOM/Chart/LegendEntryProperties.h>
#include <DOM/Chart/LegendPositionType.h>
#include <DOM/Chart/Marker.h>
#include <DOM/Chart/MarkerStyleType.h>
#include <DOM/Chart/ParentLabelLayoutType.h>
#include <DOM/Chart/PictureType.h>
#include <DOM/Chart/PieSplitCustomPointCollection.h>
#include <DOM/Chart/PieSplitType.h>
#include <DOM/Chart/QuartileMethodType.h>
#include <DOM/Chart/Rotation3D.h>
#include <DOM/Chart/StyleType.h>
#include <DOM/Chart/TickLabelPositionType.h>
#include <DOM/Chart/TickMarkType.h>
#include <DOM/Chart/TimeUnitType.h>
#include <DOM/Chart/Trendline.h>
#include <DOM/Chart/TrendlineCollection.h>
#include <DOM/Chart/TrendlineType.h>
#include <DOM/Chart/UpDownBarsManager.h>
#include <DOM/Chart/IChartSeriesGroupCollection.h>

#include <DOM/Chart/ValueStoring/DoubleChartValue.h>
#include <DOM/Chart/ValueStoring/StringChartValue.h>
#include <DOM/Chart/ValueStoring/StringOrDoubleChartValue.h>

#include <DOM/Chart/TextFormat/ChartTextFormat.h>
#include <DOM/Chart/TextFormat/ChartPortionFormat.h>

#include <DOM/Chart/Workbook/ChartDataCell.h>
#include <DOM/Chart/Workbook/ChartDataWorkbook.h>
#include <DOM/Chart/Workbook/ChartDataWorksheet.h>