#pragma once

#include <DOM/SlideShowTransition/CornerDirectionTransition.h>
#include <DOM/SlideShowTransition/EightDirectionTransition.h>
#include <DOM/SlideShowTransition/EmptyTransition.h>
#include <DOM/SlideShowTransition/FlyThroughTransition.h>
#include <DOM/SlideShowTransition/GlitterTransition.h>
#include <DOM/SlideShowTransition/InOutTransition.h>
#include <DOM/SlideShowTransition/LeftRightDirectionTransition.h>
#include <DOM/SlideShowTransition/MorphTransition.h>
#include <DOM/SlideShowTransition/OptionalBlackTransition.h>
#include <DOM/SlideShowTransition/OrientationTransition.h>
#include <DOM/SlideShowTransition/RevealTransition.h>
#include <DOM/SlideShowTransition/RippleTransition.h>
#include <DOM/SlideShowTransition/ShredTransition.h>
#include <DOM/SlideShowTransition/SideDirectionTransition.h>
#include <DOM/SlideShowTransition/SlideShowTransition.h>
#include <DOM/SlideShowTransition/SplitTransition.h>
#include <DOM/SlideShowTransition/TransitionCornerAndCenterDirectionType.h>
#include <DOM/SlideShowTransition/TransitionCornerDirectionType.h>
#include <DOM/SlideShowTransition/TransitionEightDirectionType.h>
#include <DOM/SlideShowTransition/TransitionInOutDirectionType.h>
#include <DOM/SlideShowTransition/TransitionLeftRightDirectionType.h>
#include <DOM/SlideShowTransition/TransitionMorphType.h>
#include <DOM/SlideShowTransition/TransitionPattern.h>
#include <DOM/SlideShowTransition/TransitionShredPattern.h>
#include <DOM/SlideShowTransition/TransitionSideDirectionType.h>
#include <DOM/SlideShowTransition/TransitionSoundMode.h>
#include <DOM/SlideShowTransition/TransitionSpeed.h>
#include <DOM/SlideShowTransition/TransitionType.h>
#include <DOM/SlideShowTransition/TransitionValueBase.h>
#include <DOM/SlideShowTransition/WheelTransition.h>
